### ISSUE TITLE
Sidebar Links - Opinions requested

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#113]
https://lasair-dev.lsst.ac.uk

![image](https://user-images.githubusercontent.com/3385557/216286873-156ae729-1a19-4e23-913c-262f9dc55835.png)

**Comment by thespacedoctor** [comment]
@RoyWilliams's thoughts:

My idea is multiple items in the sidebar, including multiple onramps into the documentation. Others in the team want a much sparser sidebar.

I see our users like this: Some want to read, some want to play, some want the code, some want "quickstart", some want to know what is this website, some want detail on a specific alert. They want to know who is the team, what are the publications, how to share, how to join in with an annotator. Etc etc. These are the things I imagine people want.

And yet the proposal for the sidebar is "Documentation, Filters, Watchlist, Watchmap, Schema Browser". That seems quite empty to me, and doesn't answer the users needs above. The word "documentation" is especially dull and uninviting.

https://lasair-dev.lsst.ac.uk
https://lasair.readthedocs.io/en/develop/

**Comment by thespacedoctor** [comment]
@thespacedoctor's thoughts:

Read about Lasair, Coding with Lasair and Lasair FAQ can all be consolidated into a single 'Documentation' (or "Readthedocs") link. Users can quickly get to the individual sections once they arrive at the docs.

As I have said previously, the annotator's page is documentation content and needs to live with the docs.

**Comment by gpfrancis** [comment]
- As I said previously, I think "Read about Lasair" is unclear: it should be "Documentation" or similar.
- I agree with @mFulton07 that there are lots of things users might want to read in the documentation and we should not have a top level link to them all or we will clutter up the sidebar.
- I think documentation links should be grouped together and, ideally, distinguished from other links, especially so if we have more than two of them. Perhaps have a visually distinct "top" and "bottom" section of the sidebar with functional and documentation links respectively? Or maybe the little icons are sufficient, although I have to say I didn't notice them initially. The drop-down idea would achieve the same thing.
- The traditional doc things that I would expect a top level link to are "about" (if not in a widget on the front page), "documentation" and maybe "FAQ".

**Comment by thespacedoctor** [comment]
I like the dropdown links idea @mFulton07

**Comment by genghisken** [comment]
Recording here what I've already said verbally!

I like the "(Read) About Lasair" link (though the link and the tooltip take you to the same place), but I think the others are redundant, especially the Annotators menu option, which is a replication of the documentation on readthedocs (and the tooltip takes you there). The other two links (Lasair FAQ, Coding with Lasair) take you directly to readthedocs anyway (with therefore redundant tooltip helper links).  If we want to highlight the two links, maybe they should be more prominent on the readthedocs pages.

**Comment by gpfrancis** [comment]
I'd like to repeat my request that we stick to standard terminology rather than inventing exciting new wheels which look really cute, but don't roll well.

If I go to the home web page of any software project (e.g. https://httpd.apache.org/) then I expect to see certain links:
- "Documentation" or "Docs" takes you to the top level documentation page and is almost always a top level navigation link
- "About" tells you about the thing/project: what it is, who made it, some history, how to cite, licensing, that sort of thing. May be a top level link, under documentation or sometimes elsewhere e.g. in a page footer.
- "FAQ". Could be a top level link or under documentation.

"Read About Lasair" and "Coding With Lasair" are ambiguous. I don't know where they'll take me at a glance - I have to at least read the tooltip. Also the word "Lasair" is unnecessary; they are immediately underneath the logo - we know they're going to be about Lasair! (I realise that this is partly because we've munged the information that normally lives in "about" into the top level documentation page, but that's a fault in the documentation that we should fix rather than reproduce elsewhere.)

**Comment by andyxerxes** [comment]
Ok... my two cents worth. 

(1) Lasair is not a "software project", so comparison with Apache and whatever the standard terminology for software developers may be, is not that relevant.

(2) "Documentation" is not the same as "About". The information we have is definitely documentation, and that is the term astronomers expect.

(3) It is true that most users most days will just want to get straight down to action. But there will be new users, astronomers who aren't quite sure whether they want to use it yet, and casual browsers including funding agency folk etc. For these people, the current front page is rather dry and intimidating. These people *could* be accommodated with a proper "about" link - which would NOT be the actual documentation - but in fact I think it is way better if we have an attractive front door with picture(s), general information etc, and a prominent button that says "Start Using Lasair" which jumps to the current front page with sidebar links etc. Regular users are perfectly capable of bookmarking the actual working page, and/or won't be too annoyed at having to click through. BTW, the top link could then be called "Read The Docs". The FAQ stuff at the bottom is fine.

(4) Every sidebar thing has a "Search" box. It's not obvious whether this is supposed to be "search the webpages" or "search the Lasair database".  In fact, before "filters" I think there should be a link called "Search" which allows beginners a simple position based or name based search, like we had in the old version

**Comment by mschwamb** [comment]
I agree there needs to be an about page - I also think  filters, watchlists, watchmaps, annotators, schema browser clutter the side bar - a services dropdown tab where these are all under it would make things cleaner 

And all an about and possible a getting started (though maybe the getting started shows on the front page only)

**Comment by mschwamb** [comment]
Also likely you want a news page - for announcing new releases, upgrades, potential opportunities for future hiring, etc. 

Alerce also has a publications page which is kind of nice https://alerce.science/publications/

**Comment by mschwamb** [comment]
It's also not very clear if you're stuck where to go - say a search failed with an error how would you contact the team. Maybe you want github tickets put in, but I don't know where to go from the current side bar. I think there are few ways one could do that, but currently it's not clear how to report an issue with Lasair or the website

**Comment by RoyWilliams** [comment]
The "Contact Us" link was, as I recall, voted out of the sidebar because it was too much clutter. You can get there by clicking "Read About Lasair", then its at the bottom of that very cluttered sidebar.

**Comment by RoyWilliams** [comment]
I prefer a rich sidebar so everyone can find what they are looking for, don't care if links are repeated.
Others in the team seem to like a very sparse clean look, where its wrong to have multiple routes to the same thing.

**Comment by thespacedoctor** [comment]
Rich but tidy is what I am looking for :)

**Comment by andyxerxes** [comment]
I agree strongly that now is a very good time to do some user testing, and ARC students and RAs sounds perfect. Even better if Dave could sit down with some and watch what they do.

**Comment by RoyWilliams** [comment]
Suddenly there is a big new block of work to do -- user testing. Just as we are only a week late on release. This web refresh project was supposed to be finished in December, and I pushed it to end January for breathing space. Perhaps the user testing can be folded into Lasair 4.5, due end of April, the "final ZTF release"?

**Comment by andyxerxes** [comment]
Roy - I think you have it there. Lets split this work into the two versions

**Comment by mschwamb** [comment]
I like. 

I might argue schema browser fits better  under documentation. 

I still think filters, watchlists, watchmaps, annotators might do better under a services dropdown.

**Comment by RoyWilliams** [comment]
I really don't understand why things are being hidden. I like to see what is available without having to pull back the curtain. Can we have a simple, clear, open sidebar with links:
- Filters
- Watchlists
- Watchmaps
- Annotators
- About
- Quickstart
- API & Notebooks
- FAQ
Perhaps the last four could be in a different colour as they are dox rather than index?

**Comment by thespacedoctor** [comment]
Why are we even arguing about this? I think the above is a good compromise. All the links are there and it looks tidy.

**Comment by mschwamb** [comment]
Looks good @thespacedoctor

**Comment by smarttgit** [comment]
Think this works well. 

Neutral about where the Schema Browser link goes.

**Comment by RoyWilliams** [comment]
Now it is absolutely unintelligible:
- Filter
- Watchlists
- Watchmaps
- Annotations
- Boring Old Crap

**Comment by thespacedoctor** [comment]
Final sidebar and help modal now added.

![image](https://user-images.githubusercontent.com/3385557/218037958-b1eea2ae-600c-42c0-a170-848180463309.png)

![image](https://user-images.githubusercontent.com/3385557/218037984-a3f6e6cc-8df8-459d-ba17-3711cb7ebbff.png)

<https://lasair-dev.lsst.ac.uk>
