### ISSUE TITLE
Is it possible for us to link to the avro packet data for each DIASource in the table object detections tables?

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#118]
> Is that even possible with the cassandra setup ?

Question from @smarttgit for @RoyWilliams and @genghisken

**Comment by RoyWilliams** [comment]
No problem. It just like [this query](https://github.com/lsst-uk/lasair4/blob/main/webserver/lasair/lightcurves.py#L29-L32) except put a * in place of all the named attributes.

**Comment by thespacedoctor** [comment]
I *think* Stephen was asking about the original AVRO json packets that come from the kafka stream? But might be wrong.

**Comment by RoyWilliams** [comment]
We dont keep the avro packets. We put the data they contain into cassandra. Nothing is lost.


---
Royal Observatory Edinburgh
***@***.***
07542 869986




________________________________

**Comment by smarttgit** [comment]
Great that it is easy to extract the  Information in cassandra with query easily 

Also can we make the DIASource ID name clickable (in the table of the object page) and it brings user to the full cassandra data, formatted for readability

**Comment by thespacedoctor** [comment]
![image](https://user-images.githubusercontent.com/3385557/216919598-ef25177d-f449-43c9-a1b0-95e4ec159d1a.png)

Is this the name you are speaking about? 

I will also replace or augment these export links with the full Cassandra data.

**Comment by RoyWilliams** [comment]
That export was Andy's request -- just a nice *simple* lightcurve file that can easily go into Topcat or the like. I don't think we should replace the current 5 attributes per point with the [full 120 attributes of each of the ZTF candidates](https://zwickytransientfacility.github.io/ztf-avro-alert/schema.html#ztfalertcandidate). How about a new column in the table with a popup for each candidate?

**Comment by smarttgit** [comment]
Agee with that @RoyWilliams  and @andyxerxes  - export of the simple lightcurve is good 

@thespacedoctor  - no, not there. I mean in the table of candidates (DIASources in LSST), can each of those be clickable to take you to the cassandra info on the object ?

Similar  to @RoyWilliams  suggestions of a new column in the table with a clickable popup link for each candidate.

**Comment by thespacedoctor** [comment]
Yes I finally get it ;)

**Comment by thespacedoctor** [comment]
Sneaking this through before drop day.

![Google Chrome - ZTF22aajezaq 2023-03-08 at 2 19 57 PM](https://user-images.githubusercontent.com/3385557/223737494-57f0e6dd-a6ae-423f-90ba-10a5420b6a18.gif)
