### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#120]
We have made a prototype [front page for Lasair](https://lasair-dev.lsst.ac.uk/) with an Aitoff sky that has four kinds of Sherlock-identified sky context. The markers get smaller and darker for older alerts, and are based on [this query](https://github.com/lsst-uk/lasair4/blob/feature/front-page/webserver/lasair/views.py#L38-L50).

There is RA/Dec to top-left, and coordinate grid can be toggled, also top-left. Besides eye-candy, this front page gives immediate one-click access to the object pages that are the main data product of Lasair.

Comments welcome

**Comment by mschwamb** [comment]
On firefox on MacOS once I hit the skymap while scrolling, my browser starts zooming in and out of the map and I can not easily scroll down to the bottom of the page

<img width="1302" alt="Screenshot 2023-02-06 at 8 29 49 AM" src="https://user-images.githubusercontent.com/753325/216922683-6357439b-59dc-490b-933b-8b9af7541bef.png">

There's already a lot of points on this, how is this scalable where there is 1 million transient alerts per night. This might not be the best visual for the LSST era. 

Landing pages are really important both for new users and press. If I look at this landing page, I don't immediately know what Lasair is and where to go. I think there needs to be something that guides people to an about page and also a getting started web cone search to start off with for someone completely new. 

I still think Keck Observatory does this best - they have this as the start and there is scrollable stuff below this - but it's pretty clear at entry what the website is all about. 

<img width="1295" alt="Screenshot 2023-02-06 at 8 36 57 AM" src="https://user-images.githubusercontent.com/753325/216924333-8569fcfb-ff58-4221-a4ee-d60e986453f6.png">

**Comment by RoyWilliams** [comment]
Are you suggesting we simply recycle the old page like this:
![Screenshot 2023-02-06 at 08 49 32](https://user-images.githubusercontent.com/8886481/216926630-51d0d034-ed23-4e61-ab83-8ae2e6f1238a.png)

**Comment by mschwamb** [comment]
Something more like this with a simplified sidebar (i didn't add it to the image below)

![_DSC1186](https://user-images.githubusercontent.com/753325/216928668-0e63ca0c-7408-4b95-a2ff-2fff0382346f.jpg)

**Comment by mschwamb** [comment]
The skymap I think goes better on an about page where you're explaining to people (like a new grad student or press) what Lasair does.

**Comment by RoyWilliams** [comment]
Where does "Get Started" go? 
Should they start typing SQL? (er no)
Read about the concepts? (but nobody wants to read)
Or the Aitoff sky with new alerts? Then explain how they are selected?

**Comment by mschwamb** [comment]
Follows with @andyxerxes  suggested:
(3) It is true that most users most days will just want to get straight down to action. But there will be new users, astronomers who aren't quite sure whether they want to use it yet, and casual browsers including funding agency folk etc. For these people, the current front page is rather dry and intimidating. These people could be accommodated with a proper "about" link - which would NOT be the actual documentation - but in fact I think it is way better if we have an attractive front door with picture(s), general information etc, and a prominent button that says "Start Using Lasair" which jumps to the current front page with sidebar links etc. Regular users are perfectly capable of bookmarking the actual working page, and/or won't be too annoyed at having to click through. BTW, the top link could then be called "Read The Docs". The FAQ stuff at the bottom is fine.

**Comment by RoyWilliams** [comment]
When they do "Get Started" or "Quickstart", do they get
- a wide choice of filter/watchlist/watchmap etc etc wide variety of options, or
- a tutorial with step 1, step 2, step 3 .....

**Comment by mschwamb** [comment]
It can go either way, but ultimately user testing will show whether you need to have a tutorial first or a wide choice of watchlist/map/etc. One might argue, getting started is for advanced users. Really depends on user testing. User testing should be guiding this. So once this page is made, it could be testing ARC to see how well people do with jumping in or going to the about and whether there should be an getting started for new people and a quick start for advanced users

**Comment by smarttgit** [comment]
The "where did we point" plot, really captures 

1. very useful user information that transient people want 
2. shows we are paying attention to the data 
3.  encapsulates the real time aspect of transient processing 
4. Conveys we are really on it 

I like the circle sky plot, can we think of two plots ? One on the front page and one that is clickable on sidebar ? 
@RoyWilliams already had a version of the sky plot of ZTF pointings with the FOV square sizes scaled by number of transients. Better to keep it simpler - just the footprints. Like in the ATLAS dashboard.

**Comment by smarttgit** [comment]
Cosmetics : 
I've a personal preference for the formatting of our ATLAS sky plot  http://dashboard.fallingstar.com/md/ over the version we have on our page now. I like the RA and DEC numbers, Sun, Moon, plant and ecliptic positions. 

As noted above, I like the dots for the objects discovered. But feel there's a little too much going on - suggest to drop the size scaling and the tone shading. Just simple dots for each type of transient object.

**Comment by RoyWilliams** [comment]
This is now settled.

**Comment by thespacedoctor** [comment]
Reporting here on some front-page changes:

- News item can now have HTML for links etc. It also has a nice bell icon and is dismissible. If there is no news in the 'news.txt' file or the file is missing a blank alert is no longer seen.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/3385557/223702930-6d03ca1a-586f-47a8-9a50-aff0dd1b21a4.png">

- Map now lives in its own widget with header and icon etc.
- More whitespace added around the map to help with scrolling on smaller screens. Map size also scales with screen size to keep a consistent width/height ratio (does this work for you @mschwamb and @gpfrancis)
- marker colours are a little more muted
- legend now has circles to match markers in map
- updated description text
- the usual red notification on the top right of the widget showing the object count

<img width="998" alt="image" src="https://user-images.githubusercontent.com/3385557/223704017-c479edbc-a62d-4bd0-bfab-0e02f00869ec.png">

- added a table below the map listing the transient found in the map

<img width="989" alt="image" src="https://user-images.githubusercontent.com/3385557/223704220-3935c77c-0785-4779-96aa-4a84c730616b.png">
