### ISSUE TITLE
Porting document

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#124]
Write a document with all the steps needed to port the old Lasair to version 4.2

**Comment by RoyWilliams** [comment]
[Start is here](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3136094209/Upgrading+Lasair+to+version+4.2)

Ken -- Django migrations
Dave -- Alter tables
Gareth -- Flipping DNS to lasair-status

**Comment by thespacedoctor** [comment]
Thanks @RoyWilliams - alter tables added

**Comment by RoyWilliams** [comment]
This document is ready.

**Comment by gpfrancis** [comment]
I don't think the document addresses my comment. If we're only trying to do a partial release, I don't understand why? If we're trying to do a full release then the process is wrong.

**Comment by RoyWilliams** [comment]
Can we talk on the phone about this? What time is good today?
