### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair4#137]
General review of documentation prior to release of 4.2.

**Comment by gpfrancis** [comment]
Formatting problems when viewed in Firefox (version 109.0).

<img width="1056" alt="Screenshot 2023-02-13 at 10 54 42" src="https://user-images.githubusercontent.com/30290454/218456281-bd6b2b15-15dc-4526-93c5-49cc6f4f4d1e.png">

**Comment by gpfrancis** [comment]
Page titles can get very long, e.g. "A UK Alert Stream Broker and Transient Science Platform. — lasair v4.1.0 documentation"

This means that they almost inevitably overflow anywhere they appear, e.g. browser history. Things that would help:
- make titles short and to the point
- put the word "documentation" and maybe "Lasair" up front so it doesn't get lost
- use a modified favicon so I can quickly distinguish Lasair doc pages from Lasair itself

**Comment by gpfrancis** [comment]
https://lasair.readthedocs.io/en/develop/about.html

This page generally is written in the future tense and some of it is obviously out of date. Can we bring it more up to date and talk about what Lasair does rather than what it will do?

- Should "Rubin Observatory" be a link?
- Should "LSST:UK consortium" be a link?
- Obvious cut and paste: "This submission is our formal proposal for Lasair to make that aspiration a reality by being accepted as a Community Broker and receiving the full stream." Should replace with something saying that Lasair has now been selected.
- IRIS is not linked or explained on first use - move link earlier?
- Sentence about IRIS needs rewriting. IRIS is the collaboration/community, not the cloud itself. The bit that runs in the ACF is Somerville, although we could in future use IRIS resources elsewhere too.
- Architecture diagram and its description is rather centered on the technologies used (e.g. Kafka, Cassandra) and the implementation rather than what they're being used *for*, which would be more relevant in this context. Consider revising (not urgent).
- Out of date: "Development of Lasair-LSST has guaranteed funding until 2023, with the option to apply for extension. Selection as a community broker would of course significantly enhance the probability of longer-term funding success."
- Lone reference to "tagging". Should probably refer to annotation.
- Mangled citation: "\cite{McBrien2019,Gillanders2020,Prentice2020}"
- Random "%", e.g. "%This", "%We"

**Comment by gpfrancis** [comment]
https://lasair.readthedocs.io/en/develop/quickstart.html

- Broken link: "(see (here)[about.html#extragalactic-transients) for more detail)"
- Paragraph starting "Alerts from the same place": can we make the word for the concept we're trying to define the link? e.g. instead of "combined to objects – see [here](https://lasair.readthedocs.io/en/develop/concepts/objects_sources.html) for more" how about "combined to [objects](https://lasair.readthedocs.io/en/develop/concepts/objects_sources.html)"
- Describing the filter as the one used for the alerts on the Lasair front page is out of date since we've changed the front page.
- Sentence starting "If you click on" doesn't make much sense.
- "Each object in the Lasair". When did Lasair get a definite article?

**Comment by RoyWilliams** [comment]
Gareth -- I have edited the documentation as you have suggested, thank you so much! -- Roy

**Comment by gpfrancis** [comment]
There's still a lot of documentation left to review. Do you want me to continue and, if so, should I reopen this issue or start a new one?

**Comment by RoyWilliams** [comment]
Yep please continue the review, its really valuable.
Reopen is great.
Roy

---
Royal Observatory Edinburgh
***@***.***
07542 869986





________________________________________
