### ISSUE TITLE
Add Quick Start

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#138]
Please add [Quick Start](https://lasair.readthedocs.io/en/develop/quickstart.html) to the sidebar

**Comment by thespacedoctor** [comment]
![image](https://user-images.githubusercontent.com/3385557/219613817-6699561e-b539-4ed6-a649-90522d9d3042.png)

This ok? I'll add it straight to dev if you are happy.

**Comment by RoyWilliams** [comment]
Yes please. Any chance of Quick Start instead of Quickstart or is that too boomerish?

**Comment by thespacedoctor** [comment]
sure :)

**Comment by thespacedoctor** [comment]
Now live: https://lasair-dev.lsst.ac.uk/
