### ISSUE TITLE
Review Firefox UI experience

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#142]
There seem to be a few rendering issues specific to firefox. I will review the whole app using the firefox browser and fix any glaring niggles.

**Comment by thespacedoctor** [comment]
I have tested quite a few of the components in firefox and everything seems consistent with my experience in Safari and Chrome. I can't reproduce the Lasair logo transparency issue @gpfrancis ... but I do believe you!

**Comment by gpfrancis** [comment]
I can't reproduce the logo issue this morning either, but it was always intermittent. Will let you know if it comes back.
