### ISSUE TITLE
Need a way to access to image data via API

### ISSUE THREAD

**Issue by mnicholl** [lsst-uk/lasair4#143]
Although the science/ref/diff images show up on the object pages, there doesn't seem to be a way (at least not documented in API) to easily download. Being able to get these images programatically would allow the user to run them through their own classification / analysis / ML codes

**Comment by RoyWilliams** [comment]
I'm sorry that is is not properly documented. Anyway, you can get the images through the `/api/objects` API method. I don't want to put a live token in here, but the curl version is `https://lasair-dev.lsst.ac.uk/api/objects/?objectIds=ZTF23aabplmy&token=xxxxxxxxxx&format=json`

Tp get your own token, when you are logged in on the website, click on your name at the top right, and choose “My Profile”. Your token is shown there.

In the resulting JSON, each candidate has image links like this:
"image_urls": {
			"Science": "https://lasair-dev.lsst.ac.uk/lasair/static/fits/fa9/2240410792515015000_cutoutScience.fits",
			"Template": "https://lasair-dev.lsst.ac.uk/lasair/static/fits/7d0/2240410792515015000_cutoutTemplate.fits",
			"Difference": "https://lasair-dev.lsst.ac.uk/lasair/static/fits/111/2240410792515015000_cutoutDifference.fits"
		}

**Comment by mnicholl** [comment]
Thanks Roy, I’ll give this a go!
