### ISSUE TITLE
ALPHA TEST 06: Watchmaps

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#145]
This test is all about creating and managing your watchmap.

Navigate here:

<https://lasair-dev.lsst.ac.uk/watchmaps/>

and the docs for the watchmaps are here:

<https://lasair.readthedocs.io/en/develop/core_functions/watchmaps.html>

Suggested Checklist (for guidance only ... all feedback welcome):

- [ ] Can you view and understand the watchmaps in the public gallery?
- [ ] Can you export the objects matched against a watchmap in a useful format?
- [ ] Can you export the original watchmap to in FITS/MOC format?
- [ ] Can you work out how to duplicate a watchmap from the public gallery into your My Watchmaps?
- [ ] Can you edit the name and description of a watchmap that you own?
- [ ] Can you create your own watchmap from scratch by following the documentation?
- [ ] Do you find the tutorial in the docs useful? Are there any additions you would like to be added?
- [ ] Can you toggle one of your watchmaps between active and not-active, and public and private? Do you understand these concepts?
- [ ] Can you delete one of your watchmaps?

**Comment by mnicholl** [comment]
Can you view and understand the watchmaps in the public gallery?

Yes, but would be good to label some coordinates on the plots to make it easier to interpret


 Can you export the objects matched against a watchmap in a useful format?

Export is simple and output format easy to interpret. I would suggest having separate export buttons: one in the top panel of the web page to export the map, and another in the results table panel to export the objects. It took me a moment to find how to export objects as I was assuming the top export was for the map itself.


 Can you export the original watchmap to in FITS/MOC format?

I can export easily, but I get an error when I try to read the fits file in python with MOC.load or MOC.from_fits:

   1364         path = str(path)
   1365         if format == "fits":
-> 1366             index = mocpy.spatial_moc_from_fits_file(path)
   1367             return cls(cls.__create_key, index)
   1368         elif format == "ascii":

OSError: Wrong value for keyword 'TFORM1  '. Expected: '["1I", "1J", "1K"]'. Actual: 'K'.


 Can you work out how to duplicate a watchmap from the public gallery into your My Watchmaps?

Yes


 Can you edit the name and description of a watchmap that you own?

Yes


 Can you create your own watchmap from scratch by following the documentation?

Yes, though MOC and WCS documentation is hard to understand (it doesn't explain various parameter choices, but I can't always plot my MOCs if I don't use exactly their values).

**When I created an elliptical watchmap in python, it came out very strange / wrong when I uploaded to Lasair !!!**
https://lasair-dev.lsst.ac.uk/watchmaps/36/#top


 Do you find the tutorial in the docs useful? Are there any additions you would like to be added?

I would suggest including the full code to make the rectangular skymap (it was annoying to flick back and forth between the Lasair tutorial and the MOC docs.

We may also want to include an example of making an elliptical skymap.


 Can you toggle one of your watchmaps between active and not-active, and public and private? Do you understand these concepts?

Yes


 Can you delete one of your watchmaps?

Yes. Though if MOC looks bad, would be good to be able to delete/replace only the uploaded MOC, not the whole watchmap (so avoiding having to make the name, description etc over again)


 Other:

Typo in Create New Watchmap description: "Use a Watchlmap to be alerted"

**Comment by thespacedoctor** [comment]
Great feedback Matt! Thanks. Can you make the elliptical watchmap public so we can see it?

**Comment by mnicholl** [comment]
Done. Attached is a plot of how it looks on my machine when I plot in python

[my-moc.pdf](https://github.com/lsst-uk/lasair4/files/10824850/my-moc.pdf)

**Comment by RoyWilliams** [comment]
Matt --
Sorry about the coordinates on the Aitoff thumbnail plot, I tried before and I tried again today, and I can't make it happen. 

I exported both my own watchmap file and your ellipse file, and I can read them with MOC.from_fits and visualise. I don't see the error that you had.

I made my own ellipse MOC and uploaded and it also looks a bit spotty. But I can download both your and my ellipse and visualise them. So I think the only problem is that the Aitoff thumbnail plot is not rendered right.

I have replaced the code snippet in the readthedocs with a full program.
-- Roy

**Comment by thespacedoctor** [comment]
Sorry - reopening. I have yet to harvest and act on all the feedback on this.

**Comment by thespacedoctor** [comment]
@mnicholl 

> I would suggest having separate export buttons: one in the top panel of the web page to export the map, and another in the results table panel to export the objects.

Good idea. I now have the CSV/JSON export attached to the object table widget. The is replicated across watchmap, watchlist and filter views for consistency.

![image](https://user-images.githubusercontent.com/3385557/223448945-058454f0-e9a6-4a1b-94fc-103e8b6f3599.png)

![image](https://user-images.githubusercontent.com/3385557/223448968-992b5da9-1dec-427c-ba9f-1e414ce2122c.png)

> Typo in Create New Watchmap description: "Use a Watchlmap to be alerted"

Fixed.

Re Aitoff thumbnail plots, I have raised this as a new issue (#157) to be looked at in the future.

@genghisken 

> Duplicate doesn't seem to work at all though. The form appears and edits happen, but no actual duplicate watchmap appears.

Fixed.

> The CSV and JSON exports appear redundant on this page.

Fixed so that if there are no results yet then the export options do not appear.

> Minor niggle - long named watchmap names extend beyond the window. Should probably wrap or force-wrap if the title text is too long.

I have replaced the text to not report the watchmap name, but instead reads "Update your watchmap settings:

![image](https://user-images.githubusercontent.com/3385557/223450285-2e372a5f-a5a5-4a3e-b555-04f3c85800bf.png)
