### ISSUE TITLE
ELASTICC alerts for lasair-dev

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#15]
Gareth
Please pull the topic "elasticc-test-only-3" from our friends at UW, to the Kafka system on lasair-dev, and mark it so it won't be deleted. I enclose the original information in case it is wanted.
Roy

-----------

From Rob Knop:
The original alerts with source detections will be streamed from the Kafka server at public.alerts.ztf.uw.edu:9092.  Eric Bellm tells me that all of the brokers should already be on the IP whitelist to read from that stream.  The exact topic the stream will come from is still TBD.  The simulated detections in ELAsTiCC span about 1000 simulated days, with data from about 850 simulated days during that span.  Once ELAsTiCC starts, each day we're tentatively planning to push out alerts for an interval of 12 simulated days, so that the whole stream will be delivered in just under three months.

Right now, there is a topic "elasticc-test-only-3" on that server that has about 480K test alerts in the elastic.v0_9.alert.avsc format.  The current format for this alert is here, along with the other relevant schema:

   https://github.com/LSSTDESC/elasticc/tree/main/alert_schema

The schema of this alert (really, the diaObject alert schema that's embedded) last changed a couple of weeks ago, so you'll want to make sure you have the current version.  I am now 99% certain that the alert schema will not change again before ELAsTiCC Is over.

Soon -- currently planned for Jun 15 -- we'll put up a "small" test batch of alerts.  I believe that "small" in this case will be 10% the size of the total ELAsTiCC batch (which will be ~50M alerts, so the small test batch will be ~5M alerts).  When that happens, we'll update the information in the #elasticc-comms channel on slack, and also here:

  https://portal.nersc.gov/cfs/lsst/DESC_TD_PUBLIC/ELASTICC/

At some point in the past month or so, I've received a test stream from four of the brokers.  ANTARES, FINK, and ALeRCE will be streaming via Kafka, and AMPEL will be posting alerts to us.  If each of you streaming via Kafka could put up a topic soon that has a small number of broker classification alerts in it, it would allow me to make sure that the final infrastructure for my collecting of classifications is hooked up to your stream.  After next Wednesday, when the "official" test alerts have been streamed to public.alerts.ztf.uw.edu, I'll want to start doing some volume tests to make sure that both you can all ingest the alerts from ztf, and then I can ingest the classification alerts back from you, in bulk, to make sure that things will be able to keep up.

If you have questions or other discussion, feel free to use #elasticc-comms on the LSST DESC slack, or to email me.

-Rob Knop
raknop@lbl.gov

**Comment by gpfrancis** [comment]
Done.
