### ISSUE TITLE
StreamsSerializer - Cannot open digest file

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair4#150]
Hi all

Chris F is having problems trying to access some Kafka streams.  He's getting "cannot open digest file" message from the API. Here's where it happens in the code (inside StreamsSerializer).  Can anyone explain this code to me please? Why are we opening a file at all? What generates the file?

``` python
        if topic:
            filename = lasair_settings.KAFKA_STREAMS + '/' + topic
            try:
                datafile = open(filename, 'r').read()
                data = json.loads(datafile)['digest']
                if limit:
                    data = data[:limit]
                return data
            except:
                error = 'Cannot open digest file %s' % filename
                return {"error": error}
```

**Comment by RoyWilliams** [comment]
Is it lasair-ztf or lasair-dev?
What is the filename that cannot be opened?

**Comment by genghisken** [comment]
Live system. lasair-ztf.

Error is:

```
LasairError: Bad Request:{"error":"Cannot open digest file for topic lasair_6ZooniverseTestSN-likecandidatesinlast14days"}
```

**Comment by RoyWilliams** [comment]
This is fixed now. Problem was a missing / character in the filename. Please try again.
