### ISSUE TITLE
ALPHA TEST 07: Fiilters

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#156]
This test is all about creating and managing your filters. @mFulton07 and @mnicholl I would specifically value any feedback from you as you are experienced with using filters on the old Lasair UI. @MikeeRead if you have time to have a look I would very much appreciate any thoughts you have on the new filter builder interface (you will have to sign up for a Lasair account ... an automated 3-minute process, just follow the sign-in button).

Navigate here:

<https://lasair-dev.lsst.ac.uk/filters/>

and the docs for the filters are here:

<https://lasair.readthedocs.io/en/develop/concepts/querying.html>

and here:

<https://lasair.readthedocs.io/en/develop/core_functions/make_filter.html>

Suggested Checklist (for guidance only ... all feedback welcome):

- [ ] Can you view and understand the filters in the public gallery?
- [ ] Can you export the objects matched against a filter in a useful format?
- [ ] Can you work out how to duplicate a filter from the public gallery into your My Filters?
- [ ] Can you edit the name and description of a filter that you own?
- [ ] Can you create your own filter from scratch by following the documentation? (perhaps try and reproduce a filter you have running on the production Lasair platform).
- [ ] Can you now edit this newly created filter, say to add a new column to the result set?
- [ ] Can you set the filter to be streamed via Kafka? Can you easily find the Kafka topic name for the filter?
- [ ] Do you find the tutorial in the docs useful? Are there any additions you would like to be added?
- [ ] Can you delete one of your filters?

**Comment by thespacedoctor** [comment]
> Yes, but there are too many filters in there

This is temporary. Roy and Ken have been working hard on testing all existing filters before drop day. That is why there are so many in the public gallery.

> This was really not obvious to me. When clicking on Edit Filter I can edit the actual query, but there's nowhere to edit the name and description until you click Save. I only figured out how to change the name by creating a new filter

You can also change the name and description from the settings button. This is consistent across watchlist/watchmap/filters. Hopefully once a user has used the new interface for a little while this will become clear.

> I did come across a possible bug: if I add crossmatch_tns.tns_name to the SELECT box, I do not get back any objects without a TNS name. The expected behaviour was that these objects would still appear but with a blank in the TNS name column.

I have been a little concerned about this. This is obviously the default MySQL behaviour but to users not familiar with the workings of MySQL this will not be intuitive. 2 ways forward here:

1. Leave as is but make it clear to users the behaviour to expect when joining `crossmatch_tns`
2. Manipulate the query in the background to produce the behaviour Matt expected (if no TNS match then return a row but with null in TNS name column).

I strongly favour number 2 as the resulting filters are much more scientifically powerful.

Thoughts everyone?

**Comment by RoyWilliams** [comment]
I have added an explanation of [what happens when you choose multiple tables](https://lasair.readthedocs.io/en/develop/concepts/querying.html#multiple-tables). I hope this solves the misconception.

The TNS cache is really just another watchlist, and behaves the same way as the others do.  If you want all objects coincident with your watchlist, you simply select that watchlist in the filter builder and thats what you get. I would be horrified to get a list of millions of objects NOT in my watchlist that have a NULL!

Lasair has only one kind of JOIN. You can't ask for objects that are NOT in TNS.

**Comment by mnicholl** [comment]
This makes sense (and in retrospect I should have known!) but it raises a question: is there no way to have a query that tells me everything I want to know about the light curve AND know whether or not an object is in the TNS, without losing objects that aren’t in both tables? That could be quite limiting for some things

Could TNS crossmatching be done separately from queries, and e.g. add a tns_name column to the objects table that updates ~daily? Then if I just want to know whether an object has a TNS name I wouldn’t need to join the tables in my query

**Comment by RoyWilliams** [comment]
Matt -- I'm sorry to say that the Lasair team is moving on after the release on Tuesday. We are pledged to put Lasair-ZTF in maintenance mode and concentrate on Lasair-LSST. So I don't think we will get to your excellent idea of keeping TNS status in the ZTF objects table. But we will do this for Lasair-LSST. -- Roy

**Comment by RoyWilliams** [comment]
I think we can close this one now
