### ISSUE TITLE
Object URL has changed to /objects/ from /object/ - suggest that a redirect is created

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair4#161]
The object URL (many of which will be bookmarked or coded by external API calls), has changed from /object/ to /objects/.

E.g.

https://lasair-ztf.lsst.ac.uk/objects/ZTF19aaqslxs/
was previously
https://lasair-ztf.lsst.ac.uk/object/ZTF19aaqslxs/

Can we add a redirect in urls.py?

**Comment by thespacedoctor** [comment]
fixed

**Comment by genghisken** [comment]
I have re-opened this issue. Why has the redirect disappeared?  Can change the client code, but I need some notification.
