### ISSUE TITLE
API - `lightcurves` method appears to have changed

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair4#163]
Looking at all my previous Colab notebooks which call the `lightcurves` API, the code originally returned a dictionary [`objectId`] with a list of `candidates` dictionaries (i.e detections and non-detections are split).

Now the code appears to return a flat, combined list of `candidates` and `noncandidates`, with no reference to the object ID. (Presumably the order of the lightcurves returned is the same order of the input object IDs.)

**Comment by RoyWilliams** [comment]
Fixed
