### ISSUE TITLE
Populate kafka queue with (e.g.) up to 1000 entries from run query when data flow stalled

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair4#172]
When there is little or no data flowing, users can't test their Kafka stream client code.  Would it be possible to restore the functionality to place (e.g.) up to 1000 objects from the output of "run query" into the queue? I realise that the results will be different from the objects that run through the filter nodes, but it allows coders to test code when there is a prolonged sequence of bad weather (as is currently the case). Those coders have deadlines and can't afford to wait for the weather to clear.

**Comment by genghisken** [comment]
Note that specific coders reporting problems are:
* 4MOST client
* Zooniverse SLSN client

**Comment by RoyWilliams** [comment]
This is fixed now -- except it is 10 alerts injected not 1000
