### ISSUE TITLE
Image stamps are different orientation to context map

### ISSUE THREAD

**Issue by chrisfrohmaier** [lsst-uk/lasair4#175]
Hi, I noticed that the image stamps have a different orientation to the context map.

The stamps have:
```

E <---
      |
      |
      v
      N
```

and the context map has:
```
      N
      ^
      |
      |
E <---
```

It would probably help to have the stamps match the context map.

**Comment by genghisken** [comment]
We noticed this as well last week in Oxford. E.g.:
https://lasair-ztf.lsst.ac.uk/objects/ZTF23aadjoew/.

Interesting that other brokers, e.g. ALeRCE orient the stamps the right way up. E.g.:
https://alerce.online/object/ZTF23aadjoew

They must be flipping or rotating the pixels. I think the telescope is on an equatorial mount, so north is up or down usually depending on whether the telescope has done a meridian flip. In ATLAS, we use the PA value in the header to determine whether or not the generated jpeg is flipped/rotated. Admittedly in the FITS files there's not a lot to go on - so maybe all the images are north-down!  (In which case it's just a parameter in the default JS9 representation I think.)

```
SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                  -32 / bits/pixel
NAXIS   =                    2
NAXIS1  =                   63
NAXIS2  =                   63
BUNIT   =                 'DN'
END
```
