### ISSUE TITLE
Filter match emails - urls broken

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#176]
Here is an example of the email content I received this morning:

This message is from an external sender. Please take care when responding, clicking links or opening attachments.
Your active query with Lasair on [lasair_13FBOTFinder](/query/502/)
[ZTF20aagfirh](http://lasair-ztf.lsst.ac.uk/object/ZTF20aagfirh)
[ZTF18abzqsxk](http://lasair-ztf.lsst.ac.uk/object/ZTF20aagfirh)

Fixes needed:

- lasair_13FBOTFinder query url `/query/502/` --> https://lasair-ztf.lsst.ac.uk/filters/502/
- object urls http://lasair-ztf.lsst.ac.uk/object/ZTF20aagfirh --> https://lasair-ztf.lsst.ac.uk/objects/ZTF20aagfirh (http**s** and object**s**)

**Comment by RoyWilliams** [comment]
This is fixed now
