### ISSUE TITLE
No explanation of Exponential Moving Average - note in schema and FAQ Entry

### ISSUE THREAD

**Issue by JohnAstronomer** [lsst-uk/lasair4#18]
The objects schema at https://lasair-iris.roe.ac.uk/schema has several fields containing different 'Exponential Moving Averages' which are annotated with 'see note' but there is no note - should this read see FAQ ?

The FAQ has a paragraph on Exponential Moving Average but this contains only 'Lorem Ipsum' which is not very helpful !

**Comment by RoyWilliams** [comment]
Deprecated
