### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#180]
Tried to make a watchlist with a million cones and got 
413 Request Entity Too Large -- nginx/1.18.0 (Ubuntu)
My file is 60 Mbyte
Where is the request size set?

**Comment by gpfrancis** [comment]
Try again now?

What value do we want to set the maximum request size to?

**Comment by RoyWilliams** [comment]
I think 70 Mb should be enough. Enough to cover a million cones.

Got a different error this time:
Request Entity Too Large
The requested resource does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

**Comment by RoyWilliams** [comment]
I suspect there's 3 gatekeepers: nginx, mod_wsgi, django. I'll take a look ...

**Comment by RoyWilliams** [comment]
I ran the crossmatcher, now we have a thousand Lasair objects coincident with white dwarfs
`ubuntu@lasair-dev-svc:~/lasair4/utility$ python3 run_crossmatch.py 25`

**Comment by RoyWilliams** [comment]
This is fixed now. Closing
