### ISSUE TITLE
Filter not recognising the "topic" column in the annotators table

### ISSUE THREAD

**Issue by mFulton07** [lsst-uk/lasair4#188]
I am having an issue where I can no longer make changes to this filter for querying Fastfinder annotations:
https://lasair-ztf.lsst.ac.uk/filters/124/

I'm getting the error "Your query has a syntax error near: Unknown column 'fastfinder.topic' in 'field list'" anytime I hit the save button in the filter editor, regardless if changes were made or not.

However, the original filter still runs and returns the offending column. The filter was generated on the old Lasair system (iris) and migrated over.

![Screenshot 2023-04-06 at 09 56 07](https://user-images.githubusercontent.com/58076215/231407540-4bba77b1-8e3e-48d1-8b37-926547473118.png)

**Comment by mFulton07** [comment]
Okay, it's not specific to the 'topic' column; I can't do any querying that involves the fastfinder annotator table.

**Comment by thespacedoctor** [comment]
Hi Michael, want to try and edit this filter again now?

The issue was in a query-checking function. It was reading fastfinder as a separate table instead of an alias of the annotations schema (`annotations AS fastfinder`).

@RoyWilliams how should we propagate these fixes into Lasair-LSST?

**Comment by mFulton07** [comment]
Thanks Dave, I can save changes now.

Another issue I've noticed, but unrelated to the above problem, is that my order by clause in the query is overwritten by the Object ID ordering that is performed automatically by the webpage. It's slightly annoying as I would like to order by timestamp and then classification, to see what new fast objects were found today. Shall I raise this as a separate issue?

**Comment by RoyWilliams** [comment]
These problems all fixed now
