### ISSUE TITLE
Expiry of active filter/watchlist/watchmap

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#200]
To relieve future stress on the Lasair system, we have decided to weed out old and unused filters/watchlists/watchmaps. They will not be deleted, but simply made inactive. We decided that users would be warned by email before the expiry date, and told they can just click "save" in the web interface to reset the expiry date.

Currently each model has `date_created` and `date_modified` that are identical, both have `auto_now` in the model (*), meaning updated whenever the object is saved. The `date_modified` appears nowhere in the code, only the `date_created` in the table of filters/watchlists/watchmaps. There is an additional vestigial field called `timestamp` that can be removed.

* Suggestion 1: the `date_created` should have `auto_now_add` (date set on creation). The `date_modified` should have `auto_now` (date set on save) as it does now.

* Suggestion 2: add a new field to these 3 models called `date_expire`. Every time it is saved, this field is set to `ACTIVE_EXPIRE` months in the future, where `ACTIVE_EXPIRE` is soft, i.e. in the `settings.py`.

Once these three fields are in place in the three models, and updating correctly, we can make the the cron code where emails are sent, and where things are made inactive.

* Question 1: Shall we do this on lasair-ztf then backport to lasair-lsst? A good opportunity to make sure it works. Not so difficult to backport?

(*) https://docs.djangoproject.com/en/4.2/ref/models/fields/#datefield

**Comment by gpfrancis** [comment]
I prefer option 2 because it allows for filters with non-default expiry. This might be useful for a filter relating to, for example, a GW event that is only relevant for a short time period, or, conversely, we might want to set some filters, e.g. public examples or those on which another service depends, to have a much longer expiry.

Regarding the question, I have no strong preference as to whether to include in lasair-ztf or not, nor, if so, whether to implement there first. However, if we do implent in lasair-ztf first then we are _porting_ it to lasair-lsst; backporting would be going the other way.

**Comment by RoyWilliams** [comment]
ACTION for Roy
- Change ACTION_EXPIRE to 180 (days) and change code accordingly
- Put ACTION_EXPIRE in the settings template [here](https://github.com/lsst-uk/lasair-lsst/blob/main/deploy/common/settings.py.j2)
- Make sure the actual expiration is working
- Make the emails work
- Add logging
- Put the expiration date in the email as 2023-10-27
- Make cron jobs for warning (every 7 days) and expiration (every day)
- Add cron jobs to deploy [here](https://github.com/lsst-uk/lasair-lsst/blob/main/deploy/roles/lasair_service/tasks/cron.yml)

**Comment by RoyWilliams** [comment]
How to get all the active filters:
SELECT mq_id, name, first_name, last_name, email, public, active  FROM myqueries,auth_user WHERE auth_user.id=user AND active>0;

**Comment by RoyWilliams** [comment]
Also attached is the current situation on lasair-ztf, where I have randomised the expiry times to spread out the effect. The first expirations for users will be the beginning of March, with warnings going out in February. HOWEVER three resources owned by Ken and Roy will expire at the beginning of December, so hopefully those emails will get through.

-----------
This one makes an active resource inactive, as well as sending an email, and making an entry in the Service Log. It runs every day at 1:05am. An example email is below.

# Expiration at 01:05 every day
5 1 * * * (cd /home/ubuntu/lasair4/services; python3 check_expire.py --action=expiration --days=0 --log)

at 24/10/2023, 02:05
Dear Roy Williams, Your active Lasair watchmap has recently expired and thus become inactive, and there will be no further matching of incoming alerts. To make your watchmap active again for 180 days, go to https://lasair-dev.lsst.ac.uk/watchmaps/9/ then click "Settings", "Active" or "Streaming", then "Save". Questions to lasair-help@lists.roe.ac.uk -- The Lasair Team
---------------
This one is to warn users that expiration is coming up within the next 28 days. The email is sent out every Sunday at 1:10am, so they should get 3 or 4 warnings. An example email is below.

# Expiration warning at 01:10 on Sunday
10 1 * * 0 (cd /home/ubuntu/lasair4/services; python3 check_expire.py --action=warning   --days=7 --log)

at 22/10/2023, 02:10
Dear Roy Williams, Your active Lasair watchmap will become inactive on 2023-10-23 without action from you, and there will be no further real-time matching of incoming alerts. This is to relieve pressure on the real-time pipeline. To keep your watchmap active, go to https://lasair-dev.lsst.ac.uk/watchmaps/9/ then click "Settings", then "Save". Questions to lasair-help@lists.roe.ac.uk -- The Lasair Team
---------------
