### ISSUE TITLE
Sherlock web service failing

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#24]
Gareth
The API is not running sherlock properly. This is as far as I can push it, since I don't know how your webserver is set up. I think these requests are properly formatted:

ubuntu@lasair-ztf-sherlock-0:~$ curl "http://localhost/object/ZTF21aapvmcu"
{"message": "The browser (or proxy) sent a request that this server could not understand."}

ubuntu@lasair-ztf-sherlock-0:~$ curl "http://localhost/query?ra=123&dec=23"
{"message": "The browser (or proxy) sent a request that this server could not understand."}

**Comment by gpfrancis** [comment]
```
ubuntu@lasair-ztf-bootstrap:~/lasair-deploy$ curl -H "Content-Type: application/json" -d '{ "lite": true, "ra": "1.2", "dec": "2.3" }' "http://lasair-ztf-sherlock-0/query"
{"classifications": {"transient_00000": ["ORPHAN", "No contexual information is available for this transient"]}, "crossmatches": []}
ubuntu@lasair-ztf-bootstrap:~/lasair-deploy$ curl -H "Content-Type: application/json" -d '{ "lite": true }' "http://lasair-ztf-sherlock-0/object/ZTF21aapvmcu"
{"classifications": {"ZTF21aapvmcu": ["SN", "The transient is possibly associated with <em><a href=\"https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=NGC6660&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES\">NGC6660</a></em>; an r=14.53 mag galaxy found in the NED_D/PS1/LASR catalogues. It's located 52.76\" S, 48.77\" E (14.7 Kpc) from the galaxy centre. A host distance of 42.1 Mpc(z=0.014) implies a <em>m - M =</em> 33.12."]}, "crossmatches": [{"transient_object_id": "ZTF21aapvmcu", "association_type": "SN", "catalogue_table_name": "NED D/PS1/LASR", "catalogue_object_id": "NGC6660", "catalogue_object_type": "galaxy", "raDeg": 278.652791667, "decDeg": 22.90967, "separationArcsec": 71.84, "northSeparationArcsec": "52.75514", "eastSeparationArcsec": "-48.76661", "physical_separation_kpc": 14.66, "direct_distance": 42.1, "distance": 61.17, "z": 0.01, "photoZ": null, "photoZErr": null, "Mag": 14.53, "MagFilter": "r", "MagErr": 0.0, "classificationReliability": 2, "major_axis_arcsec": null}]}
```

**Comment by RoyWilliams** [comment]
In the past, the internal Sherlock service was a GET service

https://github.com/lsst-uk/lasair4/blob/main/webserver/lasairapi/serializers.py
lines 113 and 141

Above you demonstrate that the POST works well. Would it be possible to also make the GET service work again, so I don't need to write new code for POST.

**Comment by gpfrancis** [comment]
It looks like the fundamental problem here is that the Sherlock API is built using flask-restful (https://github.com/flask-restful/flask-restful), which is not really being actively maintained any more and an underlying package has changed it's default behaviour, which in turn means that the reqparse component of flask-restful can no longer automatically convert everything on the fly.

I see three possible solutions:

1. Replace reqparse with another package such as webargs.
2. Re-write the calling code to send the request as JSON.
3. Work out how to integrate the Sherlock API into the main API so we're not maintaining two sets of API code.

I think 3 is the best (only?) long term solution, and we should probably consider it as part of the web refresh, but it also doesn't help in the short term.

I would normally suggest 1, except that I might not have time to do it this week and then I'm away for a bit.

How much work would 2 be?
