### ISSUE TITLE
URLs in Sherlock output

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#36]
I have been running the Lasair API and getting the Sherlock output. 

I noticed that the URL is wrong, where it says
    "additional_output": "http://lasair.lsst.ac.uk/api/sherlock/object/ZTF21aaopqqk",
Of course it should be lasair-ztf instead of lasair

**Comment by thespacedoctor** [comment]
I think this comes from @gpfrancis's wrapper.

**Comment by gpfrancis** [comment]
Fixed.
