### ISSUE TITLE
Create new backup database setting and run mysqldump directly on database node (not via Cluster Control)

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair4#38]
Running mysqldump via the Cluster Control server can cause replication to crash. (Jury is still out on the cause of the latest problems.)  It is recommended that the dump is run directly on the relevant target node.  This requires an additional setting for settings.yaml / settings.py

* backup_database_node
* backup_database_port

Then the script that dumps the database should use these in place of the default database settings (which go via Cluster Control).

**Comment by RoyWilliams** [comment]
This is done
