### ISSUE TITLE
Ingest creates multiple alerts

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair4#56]
Grafana says there were 29.3K alerts on 1/11/22
Created a list of alerts in ztf_ingest with a timestamp in the right range and got 81786
Downloaded these using kafkacat and got 82630 (not sure where the extras come from)
These are mostly duplicates with only 29573 unique lines.
Files are in lasair-ztf-bootstrap:~/ingest_221101

```
ubuntu@lasair-ztf-bootstrap:~/ingest_221101$ wc -l list 
81786 list
ubuntu@lasair-ztf-bootstrap:~/ingest_221101$ wc -l ingest_221101 
82630 ingest_221101
ubuntu@lasair-ztf-bootstrap:~/ingest_221101$ cat ingest_221101 | sort | uniq | wc -l
29573
```

**Comment by RoyWilliams** [comment]
The number 81786 agrees with the [status file](https://lasair-ztf.lsst.ac.uk/status/2130/) that comes from adding individual batches on 2 nodes each with 2 processes. But other tests -- that have a single large batch -- show only 29339 from that day. I think something is wrong with the multi-processing combined with the consumer, maybe the commit() is not going through properly. See [here](https://github.com/confluentinc/confluent-kafka-python/issues/925) and [here](https://stackoverflow.com/questions/60475723/trying-to-consume-messages-with-python-multiprocessing).

**Comment by RoyWilliams** [comment]
Fixed now
