### ISSUE TITLE
ALPHA TEST 03. Updating Profile

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#78]
This is the last alpha test before the holiday break. I will save the more exciting/important content-based tests until early Jan.

Navigate here <https://lasair-dev.lsst.ac.uk/> and attempt to update your profile info.

CHECKLIST:
- Can you find your profile settings easily?
- Update your first name, last name and username.
- Upload a new profile image
- Can you find your API key easily? Needed for scripting access.

Things to note:
- Profile images are now stored as base64 strings in the database and therefore backed up.

**Comment by RoyWilliams** [comment]
All works well, no problems.

**Comment by mschwamb** [comment]
There was no error when I tried to upload an image that was too big

**Comment by mschwamb** [comment]
Or rather there wasn't a user friendly error. It gave  an error on a separate page I had to navigate away from.

**Comment by mschwamb** [comment]
It was confusing that I had to hit save for the image to upload. I thought if I selected the image file it would show in the  profile image next to the paper clip. That only happened after I hit save

**Comment by mFulton07** [comment]
Uploading a file that wasn't a jpeg or png (it was a fits file) didn't return any error. All I got was an empty white box at the footer of my webpage:
![Screenshot 2022-12-28 at 12 26 13](https://user-images.githubusercontent.com/58076215/209812104-05a1adb3-fc00-4f1d-9b80-de4aa2bfde65.png)

**Comment by andyxerxes** [comment]
* found the profile settings page ok
* changed various fields ok
* uploaded image but proportions mangled - do we need to specify it should be square?
* found the API key ok

**Comment by gpfrancis** [comment]
- It isn't visually obvious that the email field is not editable (very minor issue)
- Reproduced all the same image upload issues as @mschwamb
- Images should probably be cropped to avoid distortion
- Tested various non-latin characters in name and username without problems

**Comment by thespacedoctor** [comment]
> There was no error when I tried to upload an image that was too big

I have removed the 800K limit and reduce larger image sizes on the server before saving. The onus to reduce the size has been removed from the user.

> it was confusing that I had to hit save for the image to upload. I thought if I selected the image file it would show in the profile image next to the paper clip. That only happened after I hit save

I have improved the interface to make this clearer (or less unclear anyway)

![image](https://user-images.githubusercontent.com/3385557/223415667-ebd0a909-4f5e-4a5e-9d8c-1b30a782d1d2.png)

> Uploading a file that wasn't a jpeg or png (it was a fits file) didn't return any error.

I now validate image formats:

![image](https://user-images.githubusercontent.com/3385557/223415757-009b388f-23a4-402c-a2e1-e9f942fb94e5.png)
