### ISSUE TITLE
Provide way to link dev/main docs to dev/main web UI 

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#80]
From Roy:

> How can I make a link from readthedocs? For example:
"The watchmaps page is at [/watchmaps](https://lasair-ztf.lsst.ac.uk/watchmaps)"
The link is wrong right now because not deployed yet, and will be wrong in the future when we switch to lasair-lsst or just lasair. Is there some kind of meta-tag?

**Comment by thespacedoctor** [comment]
Hi @RoyWilliams 

I have added variable injection into the Lasair docs. Environment variable values can be used with the syntax `{%MY_ENV_VAR%}` within the markdown code.

[See here for an example](https://github.com/lsst-uk/lasair4/blob/develop/docs/source/core_functions/watchlists.md?plain=1#L5)

![image.png](https://images.zenhubusercontent.com/5d247fe070c29372b512dabe/874071ea-b696-45e0-a53b-c6b0be2156b1)

Add the [result can be seen here](https://lasair.readthedocs.io/en/develop/core_functions/watchlists.html).

![image.png](https://images.zenhubusercontent.com/5d247fe070c29372b512dabe/d1c44156-2226-4fe9-864a-f18080f82f68)

I have added a code block in `docs/conf.py` to create a `lasairurl` environment variable with a value based on which git branch the current code resides in.

https://github.com/lsst-uk/lasair4/blob/develop/docs/source/conf.py#L43

Everything is working for readthedocs, but if you want to install the changes locally I think this should work (let me know if it doesn't):

```bash
cd lasair4/docs
git checkout develop
pip install --upgrade --force-reinstall -r requirements.txt
```

Obviously, you can use this same method to set/add any environment variable you would like with the docs.

**Comment by thespacedoctor** [comment]
Can I close this one?

**Comment by RoyWilliams** [comment]
Yes. Works great. Thanks!
