### ISSUE TITLE
lasair.lsst.ac.uk redirect

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#82]
Please make a HTTP redirect from lasair.lsst.ac.uk to lasair-ztf.lsst.ac.uk
It will give us a long-lived permanant URL that we can advertise
It will allow us to transition smoothly to the lsst version (by removing the redirect)

**Comment by gpfrancis** [comment]
Done. See https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3119808529/Redirect+Server
