### ISSUE TITLE
Watchmap detail times out

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair4#83]
This URL gets gateway timeout: [SDSS watchmap](https://lasair-dev.lsst.ac.uk/watchmaps/2/).
It is a watchmap with 400,000 hits and I suspect the problem is 
[this query](https://github.com/lsst-uk/lasair4/blob/feature/web-refresh/webserver/lasair/apps/watchmap/views.py#L120). 
Perhaps add 'LIMIT 1000' to the end of the query?

Might do the same with the [watchlist detail query](https://github.com/lsst-uk/lasair4/blob/feature/web-refresh/webserver/lasair/apps/watchlist/views.py#L128)

Should I do a pull request for this?

**Comment by thespacedoctor** [comment]
Hi Roy, as a stop-gap I can add the limits in with a warning to users that the query results have been capped. I think we should add pagination for queries with result sets above the limit so users can iterate through all their matches (I've made a note to do this). 

I'll add the limits now and get back to you.

**Comment by RoyWilliams** [comment]
Could also forget the pagination and just say 'only first 1000 listed' .... if they really want all 400,000 they can use the API with LIMIT and OFFSET to get the pages ....

**Comment by thespacedoctor** [comment]
That sounds like a good plan. How's this?

<https://lasair-dev.lsst.ac.uk/watchmaps/2/>

Capped at 5,000 objects. 

If you're happy I'll add the same cap to watchlists (and filters?)

**Comment by RoyWilliams** [comment]
Super! Yes for watchlists. And for filter results -- you can just select everything and there will be millions.

**Comment by thespacedoctor** [comment]
I have added this for watchlists now. Do we want the same for filters?

**Comment by RoyWilliams** [comment]
The filter detail just shows the first 1000 rows, right? So the query has a LIMIT 1000 in it, that should stop it timing out.

**Comment by thespacedoctor** [comment]
Yes, that's true. But I will add the same banner to warn users if their filter exceeds the cap to keep things consistent. 

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/3385557/215127904-3fbf8ab2-56b5-44c5-a041-d1655a9e3b0a.png">

**Comment by thespacedoctor** [comment]
Done.
