### ISSUE TITLE
 ALPHA TEST 04 -  The object details page

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#84]
This is arguably the most important component of Lasair ... the object details page. 

Here are links to 4 objects for your convenience, but please test on any object page you would like.

<https://lasair-dev.lsst.ac.uk/objects/ZTF22abycvuz/>  
<https://lasair-dev.lsst.ac.uk/objects/ZTF22aadesap/>  
<https://lasair-dev.lsst.ac.uk/objects/ZTF22aaokuja/>  
<https://lasair-dev.lsst.ac.uk/objects/ZTF22acalgpv/>  

SUGGESTED CHECKLIST:

- [ ] Consider the content on the page. Imagine this were an object you are interested in; what information/tools are missing that you would find useful?
- [ ] Find links on the page to other brokers. Are there features on the other broker pages we could/should respectfully imitate?
- [ ] How easy is it to find documentation on the individual components of the object pages?
- [ ] Many components on the page are interactive. Is this easily discoverable? How intuitive are the features to use?
- [ ] Can you export data from the page in a format that is useful to you?
- [ ] Can you view the image stamps from previous detections (i.e. not just the most recent ref-target-diff triplet)? 
- [ ] Rate your experience using these pages on a phone or tablet screen compared to the desktop experience.
- [ ] What is your favourite feature on the pages? 
- [ ] Any other suggestions for improvement?

**Comment by mschwamb** [comment]
Too much space is being take up by the header information before you get to the actual data. I would find a way to condense combine/shorten

**Comment by mschwamb** [comment]
<img width="1062" alt="Screenshot 2023-01-20 at 1 49 19 PM" src="https://user-images.githubusercontent.com/753325/213714747-4b3e6a63-be6e-4a7e-8360-3808212a13b6.png">

This seems like it could be condensed to half the current space this information occupies on the screen.

**Comment by mschwamb** [comment]
PS I like the aesthetic very much.

**Comment by thespacedoctor** [comment]
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/3385557/213715759-58d55d68-4160-46aa-ad06-ded6ed658213.png">

This is what happens on slightly larger screens. I will make this also happen on moderately sized screens and only show the single column view on small screens.

**Comment by mschwamb** [comment]
That looks better. I still think the TNS and ZTF identifier could could go in one box and then you could have the difference image lightkurve and external resources as a row below if some of the text was shortened.

**Comment by smarttgit** [comment]
When we have "Orphan",  it would be better to have the standard annotation : 

The transient is not obviously associated with any catalogued galaxy nor is it coincident with a known stellar source. 

As the current text of "No **contexual** information is available for this transient"  isn't quite accurate. We do have information, but there is no obvious counterpart (also spelling mistake!)

**Comment by smarttgit** [comment]
The lightcurve plots are only 50 days. Is this only showing what is in the last alert packet and not the full database ? 
Similarly the export only gives the 15 rows of data, but many more exist. Are we not yet pulling from the cassandra database ? That's essential of course.

**Comment by thespacedoctor** [comment]
I will fix 'Orphan' annotations.

Re lightcurves, these are the full Cassandra lightcurves. As this is the development server, the database is only ~2 months old, hence the lack of history. The plots are dynamically scaled to show the full lightcurves.

**Comment by RoyWilliams** [comment]
The old system has a much longer lightcurve for the same object:
https://lasair-dev.lsst.ac.uk/objects/ZTF22aadesap/
https://lasair-ztf.lsst.ac.uk/object/ZTF22aadesap/

**Comment by smarttgit** [comment]
> 

Would keep them other broker links in that box. I think people will assume "External Resources" are different information sources

**Comment by smarttgit** [comment]
General comment that the "Info" is really basic. As in for the total beginner. Nothing wrong with that but we may decide to increase the level of information. Leave as is for now, but worth thinking about.

**Comment by smarttgit** [comment]
General comment that the "Info" pop-out is really basic. As in for the total beginner. Nothing wrong with that but we may decide to increase the level of information. Leave as is for now, but worth thinking about.

**Comment by smarttgit** [comment]
In top left box labelled with object. Would also like to see "Latest mag" and "Latest MJD" 
Could we do that on same line as the Discovery stats, but right justified ? 

Then, when going deeper, could we have summary stat table ? 
Peak : mag, error, MJD, filter
number of good and positive detections

**Comment by smarttgit** [comment]
Presume we will have a widget for annotations ?

**Comment by smarttgit** [comment]
Is it possible for us to link to the avro packet data for each DIASource in the table ? Is that even possible with the cassandra setup ?

**Comment by smarttgit** [comment]
External resources -could we link to DECals legacy survey sky browser, I've found that quite useful : 
https://www.legacysurvey.org 
Seems to be down right now ! Should be able to link to the sky position of the transient.

**Comment by smarttgit** [comment]
Will want to have a widget for the lightcurve in flux units, which will include the forced. Presume that is straightforward.

**Comment by RoyWilliams** [comment]
When you say flux , I hope you mean difference flux. We had such trouble with ZTF trying to make apparent magnitude from difference magnitude. Assuming its diff flux:
We have this for converting m to f and vice versa, 𝑚−𝑀 = −2.5log f/𝐹, but there is the mysterious reference mag M and reference flux F. Is that right? What are the reference values?

**Comment by thespacedoctor** [comment]
> General comment that the "Info" pop-out is really basic. As in for the total beginner. Nothing wrong with that but we may decide to increase the level of information. Leave as is for now, but worth thinking about.

Most of the info tooltips have a 'learn more' link that takes the user directly to the correct section in the docs.

![image](https://user-images.githubusercontent.com/3385557/215425652-38d5604b-931c-488f-9f2e-5de74593de3b.png)

Is this what you are thinking about? Or do you want more detailed info given immediately?

**Comment by thespacedoctor** [comment]
Re vanilla lightcurves. For LSST I am imagining lightcurves to be 'flux-first' like these ATLAS lightcurves:

![image](https://user-images.githubusercontent.com/3385557/215426855-d1f0db88-ccc5-4e03-ba94-03abae025f0d.png)

ZTF mags are AB system, right? If so, I can convert these to difference μJy also.

**Comment by RoyWilliams** [comment]
AladinLite is not coming up on the object page (see below for javascript console). 
Surely this is because of last week when we messed about with the javascript loading process .....

Uncaught ReferenceError: d3 is not defined
    at celestial.min.js:4:1
    at celestial.min.js:5:1
(index):1607 Uncaught TypeError: Cannot read properties of undefined (reading 'aladin')
    at (index):1607:16

**Comment by thespacedoctor** [comment]
Hi Roy. Is the dev server on the 'develop' branch? These changes should be in the front-page feature branch.

**Comment by RoyWilliams** [comment]
The code changes I made are on front-page branch and only for the front page. But we also did all that npm and gulp in the lasair/static directory that affects the webserver itself, independent of the code branch.

**Comment by thespacedoctor** [comment]
Found and fixed the AladinLite issue. The timestamps on vendor.js and other compiled asset files were not being changed on gulp build (a known gulp bug). The django collectstatic command did not see the files as new and collecting them. I have added a 'touch' to the gulp builds to force update the file timestamps.

Note the webserver/static folder is version controlled and so (with this fix) compiled assets are branch dependent (a good thing 😀 )

**Comment by andyxerxes** [comment]
Late to the party as usual. Overall, it's fabulous! Here are various things:

links to other brokers
- personally I think these are better under "external resources" but I don't feel strongly about it
- TNS link appears twice - not necessary?

the cross links to documentation is really good.

light curve: can we mark the discovery date?

**context map: I am not getting it!**

exporting data works nicely for me. I do wonder whether to advertise an export option in the list curve block.

in useful format? yes- maybe from light curve?

I can view the various image stamps but now I have to learn JS9...
an old chestnut, but why are many missing? please explain to punters as well as me.

I tested on phone and tablet. On the phone, it more or less works but is too teeny to be useful. On an iPad, it was much more usable, but still weenier than would be nice. Font size not adjusting? In a quick go, it seemed some things were not working, but I will have another go..

**Comment by thespacedoctor** [comment]
Thank Andy. All very useful.

> light curve: can we mark the discovery date?

What are you imagining? A marker on the x-axis? 

> context map: I am not getting it!

Roy is experimenting with the front page ... JS has interfered with Aladin. Aladin (context map) is working on the develop branch.

> I do wonder whether to advertise an export option in the list curve block.

Good idea.

> I can view the various image stamps but now I have to learn JS9... an old chestnut, but why are many missing?

Over to @RoyWilliams or @genghisken on this one. Might be due to being on the development server and not production.

> On an iPad, it was much more usable, but still weenier than would be nice. Font size not adjusting?

I need to experiment on a physical iPad/tablet myself ... I'll see if I can get some time on the kids' one!

Tomorrow I will trawl all alpha test responses so far and syphon of individual issues.

**Comment by thespacedoctor** [comment]
I have now addressed most of the issues/requests from this test. Changes (soon to be deployed) are:

- Orphan comment now reads: The transient is not obviously associated with any catalogued galaxy nor is it coincident with a known stellar source.
- Latest detection details added to the object ID widget
- Extra content added to the object 'go deeper'
- Link added to DECaLS browser.
- The transient location is centred and marked with a yellow circle

![5b55c85b2e41e40886e680cc1c8ea40f](https://user-images.githubusercontent.com/3385557/216597227-df2d8536-de30-4654-9799-b0124657e315.png)

![8f2ae77f674c4558ccf5d9c8493e05a9](https://user-images.githubusercontent.com/3385557/216597256-dfd52c8a-52ca-4aac-a8b0-feb74e2ee057.png)

![6b79f8ff52db3d16246f36e13259fc87](https://user-images.githubusercontent.com/3385557/216597279-8d799c54-1ff0-4eed-9414-a7bed8b9865d.png)

![5cdf4fe2eace9b4a3560df698512a959](https://user-images.githubusercontent.com/3385557/216597294-d552bda8-a40a-4198-bb67-a5c87384cc64.png)

Small Screen Improvements for Lasair

- Fixed side bar issues where the link text width exceeds sidebar width
- Refactored the top of the object pages (especially on iPad size screens) so users can reach the data quicker. Moved external links lower down the page.
- Removed redundant second TNS link in external resources widget.
- Increased the base font size across the app. Text should now be larger on tablet screens.

![b45dd9bf579d8d0f9cdcc28acbf38d97](https://user-images.githubusercontent.com/3385557/216566869-d960f5f4-25ee-4ad5-b607-c1c7eceb57dc.png)
![960ca0ea386e209240b74b6eb98f8d51](https://user-images.githubusercontent.com/3385557/216566902-ad6eba5f-c616-417f-8530-1d50f60937fb.png)


- Lightcurves now plot flux on the left axis and mags on the right. Magnitudes are in a reverse log scale so that flux remains linear. 
- The Discovery epoch is also marked on the plot.

![fcfd0e1a26589fd934e356177a02405f](https://user-images.githubusercontent.com/3385557/216650119-504d0703-df3f-43ec-ac7a-0c652eefdcef.png)

**Comment by smarttgit** [comment]
Thinking through to LSST (totally understand what you are trying to achieve with the ZTF data here, without access to the real forced phot). 

Think 2 different plots are better in two different widgets - one with the unforced and 5-sigma limits (all in mag units) 
And the other with all the forced data (all in flux) 

Are we ok to do that for Lasair-LSST ?

**Comment by thespacedoctor** [comment]
@andyxerxes 

> I do wonder whether to advertise an export option in the list curve block.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/3385557/223707762-125292be-f16e-410f-8f4f-837876f64b6b.png">

**Comment by RoyWilliams** [comment]
The LSST flux unit is the nanoJansky [1].
The formula above has f in microJansky.
    m = −2.5log f + 23.9

Therefore if f is in nanoJansky, the correct formula is:
    m = −2.5log f + 31.4

[1] On the Choice of LSST Flux Units  https://pstn-001.lsst.io/
