### ISSUE TITLE
Add Annotator specific table schema definitions

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#88]
We currently only have a generic schema for all annotations. 

![image.png](https://images.zenhubusercontent.com/5d247fe070c29372b512dabe/5bb2d94e-cec3-4f87-87fb-012ac1bbd138)

Should we list each annotation schema separately?

**Comment by RoyWilliams** [comment]
Each annotator has the same schema. The place for creativity is in the classdict, for example fastfinder has a "KNscore" in there. Each annotator is described in https://lasair-ztf.lsst.ac.uk/annotators/ , where really the separate classdict attributes should be defined.
