### ISSUE TITLE
Fix dmdt description

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair4#91]
> in the description of the dmdt parameters, I think it would be useful to specify the units of the dt, so that one can easily compute the delta he needs to look for.    

This was a request from a user. Here is the current description:

![image.png](https://images.zenhubusercontent.com/5d247fe070c29372b512dabe/e0b0db11-2f68-40d1-bf3b-b25db289e547)

**Comment by RoyWilliams** [comment]
Its mags per day. BUT the dmdt is crap. Often there are two detections with very small deltaT between them, which means dmdt is a big random number with a massive error. I am working with Stephen to make a much better estimate of rise rate and colour change that will actually be useful.

**Comment by thespacedoctor** [comment]
I'll fix the description for now and warn users to check the error.
